### ISSUE TITLE
Python traceback when run on a directory of task files, but not on each file individually

### ISSUE THREAD

**Issue by emsecrist** [thegeeklab/ansible-later#117]
When executing ansible-later on a directory of ansible task files a python traceback occurs. No errors are seen when ansible-later is run on each task file individually. Please see the output from both scenarios below.
```
$ ansible-later tasks
WARNING: Task tasks/cmk_agent.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

WARNING: Task tasks/common_dirs.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

WARNING: Task tasks/common.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

WARNING: Task tasks/main.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

WARNING: Task tasks/nessus_agent.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

WARNING: Task tasks/server_stop_start.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

WARNING: Task tasks/splunk_uf.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

ERROR: [ANSIBLE0004] Standard 'YAML should use consistent number of spaces around variables' not met:
... tasks/cmk_agent.yml:9: no suitable numbers of spaces (min: 1 max: 1)

ERROR: [ANSIBLE0004] Standard 'YAML should use consistent number of spaces around variables' not met:
... tasks/cmk_agent.yml:17: no suitable numbers of spaces (min: 1 max: 1)

ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/cmk_agent.yml:16: name 'ensure running services for cmk' should start with uppercase

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... tasks/cmk_agent.yml:7: too many blank lines (2 > 1)

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... tasks/cmk_agent.yml:11: wrong indentation: expected 4 but found 5

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... tasks/cmk_agent.yml:14: wrong indentation: expected 4 but found 5

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... tasks/cmk_agent.yml:19: wrong indentation: expected 4 but found 5

ERROR: [ANSIBLE0001] Standard 'Single tasks should be separated by empty line' not met:
... tasks/common_dirs.yml:1: missing task separation (required: 1 empty line)

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... tasks/common_dirs.yml:4: wrong indentation: expected 4 but found 6

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... tasks/common_dirs.yml:1: missing document start "---"

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... tasks/main.yml:21: missing document end "..."

ERROR: [ANSIBLE0001] Standard 'Single tasks should be separated by empty line' not met:
... tasks/common.yml:1: missing task separation (required: 1 empty line)

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... tasks/nessus_agent.yml:38: missing document end "..."

ERROR: [ANSIBLE0011] Standard 'Commands should be idempotent' not met:
... tasks/common.yml:1: commands should either read information (and thus set changed_when) or not do something if it has already been done (using creates/removes) or only do it if another check has a particular result (when)

ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/server_stop_start.yml:3: name 'jrs_maint template' should start with uppercase

ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/server_stop_start.yml:12: name 'start template' should start with uppercase

ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/server_stop_start.yml:21: name 'stop template' should start with uppercase

ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/server_stop_start.yml:30: name '0_reboot template' should start with uppercase

ERROR: [ANSIBLE0007] Standard 'Name of tasks and handlers must be formatted' not met:
... tasks/server_stop_start.yml:39: name 'activate new reboot init script' should start with uppercase

ERROR: [ANSIBLE0011] Standard 'Commands should be idempotent' not met:
... tasks/server_stop_start.yml:39: commands should either read information (and thus set changed_when) or not do something if it has already been done (using creates/removes) or only do it if another check has a particular result (when)

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... tasks/common.yml:4: too many blank lines (2 > 1)

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... tasks/common.yml:44: too many blank lines (2 > 1)

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... tasks/server_stop_start.yml:1: too many blank lines (1 > 0)

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... tasks/common.yml:36: wrong indentation: expected 4 but found 7

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... tasks/server_stop_start.yml:3: missing document start "---"

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... tasks/common.yml:1: missing document start "---"

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... tasks/server_stop_start.yml:41: missing document end "..."

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... tasks/common.yml:84: missing document end "..."

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... tasks/splunk_uf.yml:53: missing document end "..."

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/secriste/.local/lib/python3.6/site-packages/ansiblelater/__main__.py", line 94, in _review_wrapper
    return candidate.review(settings, lines)
  File "/home/secriste/.local/lib/python3.6/site-packages/ansiblelater/command/candidates.py", line 120, in review
    result = standard.check(self, settings.config)
  File "/home/secriste/.local/lib/python3.6/site-packages/ansiblelater/rules/yamlfiles.py", line 50, in check_native_yaml
    errors.append(Error(task["__line__"], description))
KeyError: '__line__'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/secriste/.local/bin/ansible-later", line 11, in <module>
    sys.exit(main())
  File "/home/secriste/.local/lib/python3.6/site-packages/ansiblelater/__main__.py", line 80, in main
    errors = (sum(p.map(_review_wrapper, tasks)))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: '__line__'
```

Here is the output when running ansible-later on each file individually from within the tasks directory:
```
$ for i in `ls`; do echo $i; ansible-later $i; done
cmk_agent.yml
WARNING: Playbook cmk_agent.yml does not present standards version. Using latest standards version 0.1

ERROR: [ANSIBLE0004] Standard 'YAML should use consistent number of spaces around variables' not met:
... cmk_agent.yml:9: no suitable numbers of spaces (min: 1 max: 1)

ERROR: [ANSIBLE0004] Standard 'YAML should use consistent number of spaces around variables' not met:
... cmk_agent.yml:17: no suitable numbers of spaces (min: 1 max: 1)

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... cmk_agent.yml:7: too many blank lines (2 > 1)

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... cmk_agent.yml:11: wrong indentation: expected 4 but found 5

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... cmk_agent.yml:14: wrong indentation: expected 4 but found 5

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... cmk_agent.yml:19: wrong indentation: expected 4 but found 5

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... cmk_agent.yml:20: missing document end "..."

common_dirs.yml
WARNING: Playbook common_dirs.yml does not present standards version. Using latest standards version 0.1

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... common_dirs.yml:4: wrong indentation: expected 4 but found 6

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... common_dirs.yml:1: missing document start "---"

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... common_dirs.yml:35: missing document end "..."

common.yml
WARNING: Playbook common.yml does not present standards version. Using latest standards version 0.1

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... common.yml:4: too many blank lines (2 > 1)

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... common.yml:44: too many blank lines (2 > 1)

ERROR: [LINT0002] Standard 'YAML should be correctly indented' not met:
... common.yml:36: wrong indentation: expected 4 but found 7

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... common.yml:1: missing document start "---"

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... common.yml:84: missing document end "..."

main.yml
WARNING: Playbook main.yml does not present standards version. Using latest standards version 0.1

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... main.yml:21: missing document end "..."

nessus_agent.yml
WARNING: Playbook nessus_agent.yml does not present standards version. Using latest standards version 0.1

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... nessus_agent.yml:38: missing document end "..."

server_stop_start.yml
WARNING: Playbook server_stop_start.yml does not present standards version. Using latest standards version 0.1

ERROR: [LINT0001] Standard 'YAML should not contain unnecessarily empty lines' not met:
... server_stop_start.yml:2: too many blank lines (2 > 0)

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... server_stop_start.yml:4: missing document start "---"

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... server_stop_start.yml:42: missing document end "..."

splunk_uf.yml
WARNING: Playbook splunk_uf.yml does not present standards version. Using latest standards version 0.1

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... splunk_uf.yml:53: missing document end "..."

sysctl.yml
WARNING: Playbook sysctl.yml does not present standards version. Using latest standards version 0.1

ERROR: [LINT0004] Standard 'YAML should contain document start marker' not met:
... sysctl.yml:1: missing document start "---"

ERROR: [LINT0009] Standard 'YAML should contain document end marker' not met:
... sysctl.yml:6: missing document end "..."
```

**Comment by xoxys** [comment]
Thanks for your report. Can you please create a minimal public GH repository to reproduce this error?

**Comment by emsecrist** [comment]
Public GH repo created here
https://github.com/emsecrist/ansible-later-issue-117

**Comment by xoxys** [comment]
Thanks! I've prepared a fix and will tag a new release after the merge.

**Comment by emsecrist** [comment]
Thanks! Appreciate the quick help.
