### ISSUE TITLE
win_shell module leads to a crash

### ISSUE THREAD

**Issue by passe4wedo** [thegeeklab/ansible-later#266]
Hi everybody, I have configured this simple role file which uploads a .ps1 script to a Windows instance and runs it:

```
- name: "Templating the PowerShell script"
  win_template:
    src: "install-cert.ps1.j2"
    dest: 'C:\temp\install-cert.ps1'

- name: "Running the script"
  win_shell: 'C:\temp\install-cert.ps1'
```

if I try to execute ansible-later, it throws the following error:
```
$> ansible-later roles/vm_deploy/tasks/install_cert.yml -vv

WARNING: Task roles/vm_deploy/tasks/install_cert.yml is in a role that contains a meta/main.yml without a declared standards version. Using latest standards version 0.1

INFO: Reviewing all of Task (roles/vm_deploy/tasks/install_cert.yml)

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/leo/.local/lib/python3.6/site-packages/ansiblelater/__main__.py", line 94, in _review_wrapper
    return candidate.review(settings, lines)
  File "/home/leo/.local/lib/python3.6/site-packages/ansiblelater/command/candidates.py", line 120, in review
    result = standard.check(self, settings.config)
  File "/home/leo/.local/lib/python3.6/site-packages/ansiblelater/rules/yamlfiles.py", line 50, in check_native_yaml
    errors.append(Error(task["__line__"], description))
KeyError: '__line__'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/leo/.local/bin/ansible-later", line 11, in <module>
    sys.exit(main())
  File "/home/leo/.local/lib/python3.6/site-packages/ansiblelater/__main__.py", line 80, in main
    errors = (sum(p.map(_review_wrapper, tasks)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: '__line__'
```
I'm currently editing such .yml file with VSCode, I also confirm that the charset is UTF-8 and the newline char is set to LF (unix style).

Could you please help me to understand why this happens?

**Comment by xoxys** [comment]
Hi, what Version of `ansible-later` do you use?

**Comment by xoxys** [comment]
Looks like you still use Python 3.6 which is also not supported anymore.

**Comment by passe4wedo** [comment]
Thank you for your quick reply.
After the Python upgrade to the version 3.8.0 everything works like a charm.
