### ISSUE TITLE
Exception raised for wrong configuration

### ISSUE THREAD

**Issue by CarstenGrohmann** [thegeeklab/ansible-later#519]
Hi,

I've got a nested exception after I created a configuration file w/o quotes for `version: 0.2`:

```
# cat .later.yml 
# Global settings for all defined rules
rules:

  # Standard version to use. Standard version set in a roles meta file
  # or playbook will takes precedence.
  version: 0.2


#  ansible-later 
Traceback (most recent call last):
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/ansiblelater/settings.py", line 188, in _validate
    anyconfig.validate(config, self.schema, ac_schema_safe=False)
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/anyconfig/schema/jsonschema.py", line 95, in validate
    return _validate(data, schema, ac_schema_safe, **options)
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/anyconfig/schema/jsonschema.py", line 56, in _validate
    jsonschema.validate(
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: 0.2 is not of type 'string'

Failed validating 'type' in schema['properties']['rules']['properties']['version']:
    {'type': 'string'}

On instance['rules']['version']:
    0.2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/carsten/virtualenv/bin/ansible-later", line 8, in <module>
    sys.exit(main())
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/ansiblelater/__main__.py", line 68, in main
    settings = Settings(args=args)
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/ansiblelater/settings.py", line 41, in __init__
    self.config = self._get_config()
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/ansiblelater/settings.py", line 85, in _get_config
    if self._validate(sdict):
  File "/home/carsten/virtualenv/lib64/python3.10/site-packages/ansiblelater/settings.py", line 195, in _validate
    validator=e.validator, schema=format_as_index(list(e.relative_schema_path)[:-1])
TypeError: format_as_index() missing 1 required positional argument: 'indices'
```

ansible-later runs fine, with a quoted `version: "0.2"`.

Maybe the parser here can also accept float values and then convert them automatically to strings.

Regards,
Carsten

**Comment by xoxys** [comment]
Adding a dynamic way to auto-convert values that are required to be a string is quite expensive, but at least the nested exception was not intended and need to be fixed.

**Comment by CarstenGrohmann** [comment]
I can confirm, that #520 solves the issue:

```
$ ansible-later 
CRITICAL: Error while loading configuration:
... Failed validating 'type' at rules['version']: 0.2 is not of type 'string'
```

Thank you,
Carsten
