### ISSUE TITLE
exclude_files: do not work

### ISSUE THREAD

**Issue by alexey-vostrikov** [thegeeklab/ansible-later#647]
I made configuration to exclude .gitlab-ci.yml from linting
Because it uses externally defined yaml tags !reference
But ansible-later crashed

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/ansiblelater/__main__.py", line 98, in _review_wrapper
    return candidate.review()
           ^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/ansiblelater/candidate.py", line 98, in review
    result = standard.check(self, self.config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/DevOps/steplogic/ansible_common_collection/../../../.local/lib/python3.11/site-packages/ansiblelater/rules/CheckCommandInsteadOfArgument.py", line 35, in check
    tasks, errors = self.get_normalized_tasks(candidate, settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/ansiblelater/standard.py", line 137, in get_normalized_tasks
    yamllines = parse_yaml_linenumbers(f, candidate.path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/ansiblelater/utils/yamlhelper.py", line 539, in parse_yaml_linenumbers
    data = loader.get_single_data() or []
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/aborland/.local/lib/python3.11/site-packages/ansible/parsing/yaml/constructor.py", line 120, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!reference'
  in ".gitlab-ci.yml", line 24, column 7
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aborland/.local/bin/ansible-later", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aborland/.local/lib/python3.11/site-packages/ansiblelater/__main__.py", line 88, in main
    errors = (sum(p.map(_review_wrapper, tasks)))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!reference'
  in ".gitlab-ci.yml", line 24, column 7
```

**Comment by xoxys** [comment]
Please provide a minimal example repo to reproduce this issue.

**Comment by xoxys** [comment]
Cant reproduce. Unknown YAML tags should be caught gracefully, and excluding files works here was well. If the issue still exists, please create a new one and provider proper information.

**Comment by alexey-vostrikov** [comment]
> Please provide a minimal example repo to reproduce this issue.
https://github.com/alexey-vostrikov/ansible-later-bug-example

**Comment by alexey-vostrikov** [comment]
You can see that: .later.yml  contains
```
# Global settings for all defined rules
rules:
  # list of files to exclude
  exclude_files:
  - .gitlab-ci.yml
```
